[package]
name = "ipopt-ad"
version = "0.1.0"
authors = ["Philipp Rehner <prehner@ethz.ch>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Blackbox NLP solver using IPOPT and automatic differentiation"
readme = "README.md"
repository = "https://github.com/prehner/ipopt-ad"
keywords = ["optimization"]
categories = ["science"]

[dependencies]
ipopt = { git = "https://github.com/prehner/ipopt-rs", branch = "static_linking" }
num-dual = "0.13"
nalgebra = "0.34"

[dev-dependencies]
approx = "0.5"
